name: office_fit
description: simple fitness reminders at office

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.0.1
  intl: ^0.15.7
  redux: ^3.0.0
  flutter_redux: ^0.5.2
  shared_preferences: ^0.4.2
  android_job_scheduler:
      git:
        url: https://github.com/babanomania/android_job_scheduler
  flutter_local_notifications: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - images/onboard.jpg
     - images/drink_water.png
     - images/stand_up.png
     - images/stretch.png
     - images/walk.png
     - images/efficient.png
     - images/procrastination.png
